### ISSUE TITLE
메인 화면의 헤더에 있는 사용자 프로필 클릭시 나오는 드롭다운 메뉴 추가

### ISSUE THREAD

**Issue by datalater** [prgrms-web-devcourse/Team_BbungCles_Devnity_FE#59]
## 💁 설명

메인 화면의 헤더에 있는 사용자 프로필을 클릭하면 나와야 하는 드롭다운 메뉴를 추가한다

### 관련 유저 시나리오

- (헤더의 사용자 프로필 이미지를 클릭하여 나온) 드롭다운 메뉴에서 프로필을 클릭하면, 자기소개 상세 조회 페이지로 이동한다
- (헤더의 사용자 프로필 이미지를 클릭하여 나온) 드롭다운 메뉴에서 내 모임 관리를 클릭하면, 내 모임 관리 페이지로 이동한다
- (헤더의 사용자 프로필 이미지를 클릭하여 나온) 드롭다운 메뉴에서 로그아웃을 클릭하면, 로그아웃이 되며 로그인 페이지로 이동한다

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] 사용자 이미지 클릭하면 나와야 하는 드롭다운 메뉴 UI 추가
- [ ] 각 드롭다운 메뉴 UI를 클릭했을 때 페이지 이동을 위한 라우팅 처리 추가

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

없음

**Comment by rkdvnfma90** [comment]
로그아웃의경우 `localStorage`에 저장되어 있는 토큰을 삭제 후 `login` 페이지로 라우팅 처리할 예정이신가요!? 그냥 궁금해서 여쭤봅니다 ㅎㅎㅎ

**Comment by datalater** [comment]
> @datalater  로그아웃의경우 `localStorage`에 저장되어 있는 토큰을 삭제 후 `login` 페이지로 라우팅 처리할 예정이신가요!? 그냥 궁금해서 여쭤봅니다 ㅎㅎㅎ

네 그래야할 것 같아요 

1. 로컬스토리지 삭제하고
2. axios 인스턴스 토큰 삭제하고

아마 이렇지 않을까 싶네요ㅎㅎ

**Comment by rkdvnfma90** [comment]
@datalater axios 인스턴스 토큰은 별도로 삭제 안해도 될 것 같아요, 그 이유는 `necessaryAuthAxiosInstance.ts` 파일의 `axiosInstance.interceptors.request`에서 요청이 있을 때 마다 로컬스토리지에서 토큰을 가져오기 때문에 로그아웃 시점에서만 지워도 될 것 같습니다! 혹시나 아니라면 바로 알려주세요~! 😁

```ts
// necessaryAuthAxiosInstance.ts

const token = getLocalStorageItem(login.localStorageKey.TOKEN, "");

axiosInstance.interceptors.request.use(
  (config) => {
    const newConfig = config;
    newConfig.headers.Authorization = `Bearer ${token}`;

    return newConfig;
  },
  (error) => Promise.reject(error)
);

```

**Comment by datalater** [comment]
아하 자동으로 가져오는군요! 안 지워도 되겠네요 😁
